server:
  port: 8081

spring:
  application:
    name: library-management-system
  datasource:
    url: jdbc:postgresql://localhost:5432/library_management_db
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      format_sql: true
      show-sql: true
    database: postgresql
    open-in-view: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /library-api.html
    operationsSorter: method
    tagsSorter: alpha
    default-sort: method,asc
