#Library Management System Configuration
spring:
  application:
    name: library-management-system
  datasource:
    url: jdbc:postgresql://localhost:5432/library_management_db
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      format_sql: true
      show-sql: true
    database: postgresql
    open-in-view: true

logging:
  file:
    name: logs/dev.log
  level:
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  file-size: 100MB


#Server Configuration:
server:
  port: 8081

#Management Endpoints Configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

#Springdoc Configuration:
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /library-api.html
    operationsSorter: method
    tagsSorter: alpha
    default-sort: method,asc
