name: Library Management System CI

on:
  push:
    branches:
      - main  # Adjust if your default branch name differs
  pull_request:
    branches:
      - main  # Adjust if your default branch name differs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # Cache Maven dependencies
      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      # Build and deploy the common project to the local repository
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven

      - name: Build common project
        run: |
          cd common
          mvn clean install -DskipTests

      - name: Build and test library-management-system
        run: |
          cd library-management-system
          mvn clean install
